export default {
    data() {
        return {
            All_IDs: {
                YiSangIDs: {
                    IDs: {
                        "Effloresced E.G.O::Spicebush YiSang": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Blade Lineage Salsu YiSang": { rarity: "Rarity000", uptied: "0", level:0 },
                        "W Corp. L3 Cleanup Agent YiSang": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Seven Assoc. South Section 6 YiSang": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Molar Office Fixer YiSang": { rarity: "Rarity00", uptied: "0", level:0 },
                        "The Pequod First Mate Yi Sang": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Dieci South Section 4 Yi Sang": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner YiSang": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Crow's Eye View": { rarity: "Z", uptied: "0", level:0 },
                        "4th Match Flame": { rarity: "T", uptied: "0", level:0 },
                        "Wishing Cairn": { rarity: "T", uptied: "0", level:0 },
                        "Dimension Shredder": { rarity: "H", uptied: "0", level:0 },
                        "Sunshower": { rarity: "W", uptied: "0", level:0 }
                    },
                },
                FaustIDs: {
                    IDs: {
                        "Seven Assoc. South Section 4 Faust": { rarity: "Rarity000", uptied: "0", level:0 },
                        "The One Who Grips Faust": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Lobotomy E.G.O::Regret Faust": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Lobotomy Corp Remnant Faust": { rarity: "Rarity00", uptied: "0", level:0 },
                        "W Corp. L2 Cleanup Agent Faust": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Zwei Assoc. South Section 4 Faust": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Faust": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Representation Emitter": { rarity: "Z", uptied: "0", level:0 },
                        "Hex Nail": { rarity: "T", uptied: "0", level:0 },
                        "9:2": { rarity: "T", uptied: "0", level:0 },
                        "Telepole": { rarity: "H", uptied: "0", level:0 },
                        "Fluid Sac": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                DonIDs: {
                    IDs: {
                        "Cinq Assoc. South Section 5 Director Don Quixote": { rarity: "Rarity000", uptied: "0", level:0 },
                        "W Corp. L3 Cleanup Agent Don Quixote": { rarity: "Rarity000", uptied: "0", level:0 },
                        "The Middle Little Sister Don Quixote": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Shi Assoc. South Section 5 Director Don Quixote": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Lobotomy E.G.O::Lantern Don Quixote": { rarity: "Rarity00", uptied: "0", level:0 },
                        "N Corp. Mittelhammer Don Quixote": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Don Quixote": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "La Sangre de Sancho": { rarity: "Z", uptied: "0", level:0 },
                        "Lifetime Stew": { rarity: "T", uptied: "0", level:0 },
                        "Fluid Sac": { rarity: "H", uptied: "0", level:0 },
                        "Telepole": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                RyoshuIDs: {
                    IDs: {
                        "W Corp. L3 Cleanup Agent Ryoshu": { rarity: "Rarity000", uptied: "0", level:0 },
                        "R.B. Chef de Cuisine Ryoshu": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Kurokumo Clan Wakashu Ryoshu": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Seven Assoc. South Section 6 Ryoshu": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCCB Assistant Manager Ryoshu": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Ryoshu": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Forest for the Flames": { rarity: "Z", uptied: "0", level:0 },
                        "Soda": { rarity: "ZnotOriginal", uptied: "0", level:0 },
                        "Red Eyes": { rarity: "T", uptied: "0", level:0 },
                        "Blind Obsession": { rarity: "T", uptied: "0", level:0 },
                        "4th Match Flame": { rarity: "H", uptied: "0", level:0 },
                        "Red Eyes (Open)": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                MeurIDs: {
                    IDs: {
                        "R Corp. 4th Pack Rhino Meursault": { rarity: "Rarity000", uptied: "0", level:0 },
                        "N Corp. GroBHammer Meursault": { rarity: "Rarity000", uptied: "0", level:0 },
                        "W Corp. L2 Cleanup Agent Meursault": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Liu Assoc. South Section 6 Meursault": { rarity: "Rarity00", uptied: "0", level:0 },
                        "The Middle Little Brother Meursault": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Rosespanner Workshop Fixer Meursault": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Meursault": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Chains of Others": { rarity: "Z", uptied: "0", level:0 },
                        "Screwloose Wallop": { rarity: "T", uptied: "0", level:0 },
                        "Regret": { rarity: "T", uptied: "0", level:0 },
                        "Capote": { rarity: "H", uptied: "0", level:0 },
                        "Pursuance": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                HongLuIDs: {
                    IDs: {
                        "Ting Tang Gang Gangleader Hong Lu": { rarity: "Rarity000", uptied: "0", level:0 },
                        "K Corp. Class 3 Excision Staff Hong Lu": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Dieci South Section 4 Hong Lu": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Kurokumo Clan Wakashu Hong Lu": { rarity: "Rarity00", uptied: "0", level:0 },
                        "W Corp. L2 Cleanup Agent Hong Lu": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Liu Assoc. South Section 5 Hong Lu": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Hook Office Fixer Hong Lu": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Hong Lu": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Land of Illusion": { rarity: "Z", uptied: "0", level:0 },
                        "Roseate Desire": { rarity: "T", uptied: "0", level:0 },
                        "Soda": { rarity: "T", uptied: "0", level:0 },
                        "Dimension Shredder": { rarity: "H", uptied: "0", level:0 },
                        "Effervescent Corrosion": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                HeathIDs: {
                    IDs: {
                        "R Corp. 4th Pack Rabbit Heathcliff": { rarity: "Rarity000", uptied: "0", level:0 },
                        "The Pequod Harpooneer Heathcliff": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Lobotomy E.G.O::Sunshower Heathcliff": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Shi Assoc. South Section 5 Heathcliff": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Seven Assoc. South Section 4 Heathcliff": { rarity: "Rarity00", uptied: "0", level:0 },
                        "N Corp. Kleinhammer Heathcliff": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Heathcliff": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Bodysack": { rarity: "Z", uptied: "0", level:0 },
                        "Holiday": { rarity: "ZnotOriginal", uptied: "0", level:0 },
                        "AEDD": { rarity: "T", uptied: "0", level:0 },
                        "Ya Sunyata Tad Rupam": { rarity: "H", uptied: "0", level:0 },
                        "Telepole": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                IshIDs: {
                    IDs: {
                        "Molar Boatworks Fixer Ishmael": { rarity: "Rarity000", uptied: "0", level:0 },
                        "R Corp. 4th Pack Reindeer Ishmael": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Liu Assoc. South Section 4 Ishmael": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Lobotomy E.G.O::Sloshing Ishmael": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Shi Assoc. South Section 5 Ishmael": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCCB Assistant Manager Ishmael": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Ishmael": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Snagharpoon": { rarity: "Z", uptied: "0", level:0 },
                        "Roseate Desire": { rarity: "T", uptied: "0", level:0 },
                        "Capote": { rarity: "T", uptied: "0", level:0 },
                        "Ardor Blossom Star": { rarity: "H", uptied: "0", level:0 },
                        "Blind Obsession": { rarity: "W", uptied: "0", level:0 },
                    },
                },
                RodionIDs: {
                    IDs: {
                        "Kurokumo Clan Wakashu Rodion": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Rosespanner Workshop Rep Rodion": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Dieci Assoc. South Section 4 Rodion": { rarity: "Rarity000", uptied: "0", level:0 },
                        "LCCB Assistant Manager Rodion": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Zwei Assoc. South Section 5 Rodion": { rarity: "Rarity00", uptied: "0", level:0 },
                        "N Corp. Mittelhammer Rodion": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Rodion": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "What is Cast": { rarity: "Z", uptied: "0", level:0 },
                        "Rime Shank": { rarity: "T", uptied: "0", level:0 },
                        "Effervescent Corrosion": { rarity: "T", uptied: "0", level:0 },
                        "4th Match Flame": { rarity: "H", uptied: "0", level:0 },
                        "Pursuance": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                SinclairIDs: {
                    IDs: {
                        "Blade Lineage Salsu Sinclair": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Cinq Association South Section 4 Director Sinclair": { rarity: "Rarity000", uptied: "0", level:0 },
                        "The One Who Shall Grip Sinclair": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Zwei Assoc. South Section 6 Sinclair": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Los Mariachis Jefe Sinclair": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Lobotomy E.G.O::Red Sheet Sinclair": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Molar Boatworks Fixer Sinclair": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Sinclair": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Branch of Knowledge": { rarity: "Z", uptied: "0", level:0 },
                        "Impending Day": { rarity: "T", uptied: "0", level:0 },
                        "Lifetime Stew": { rarity: "T", uptied: "0", level:0 },
                        "Lantern": { rarity: "H", uptied: "0", level:0 },
                        "9:2": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                OutisIDs: {
                    IDs: {
                        "Seven Assoc. South Section 6 Director Outis": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Lobotomy E.G.O::Magic Bullet Outis": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Molar Office Fixer Outis": { rarity: "Rarity000", uptied: "0", level:0 },
                        "G Corp. Head Manager Outis": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Blade Lineage Cutthroat Outis": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Cinq Association South Section 4 Outis": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Outis": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "To pathos Mathos": { rarity: "Z", uptied: "0", level:0 },
                        "Sunshower": { rarity: "T", uptied: "0", level:0 },
                        "Ya Sunyata Tad Rupam": { rarity: "T", uptied: "0", level:0 },
                        "Ebony Stem": { rarity: "H", uptied: "0", level:0 },
                        "Holiday": { rarity: "H", uptied: "0", level:0 },
                    },
                },
                GregorIDs: {
                    IDs: {
                        "G Corp. Manager Corporal Gregor": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Twinhook Pirates First Mate Gregor": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Zwei Assoc. South Section 4 Gregor": { rarity: "Rarity000", uptied: "0", level:0 },
                        "Rosespanner Workshop Fixer Gregor": { rarity: "Rarity00", uptied: "0", level:0 },
                        "Liu Assoc. South Section 6 Gregor": { rarity: "Rarity00", uptied: "0", level:0 },
                        "R.B. Sous-chef Gregor": { rarity: "Rarity00", uptied: "0", level:0 },
                        "LCB Sinner Gregor": { rarity: "Rarity0", uptied: "0", level:0 },
                    },
                    EGOs: {
                        "Suddenly,One Day": { rarity: "Z", uptied: "0", level:0 },
                        "Legerdemain": { rarity: "ZnotOriginal", uptied: "0", level:0 },
                        "AEDD": { rarity: "T", uptied: "0", level:0 },
                        "Lantern": { rarity: "H", uptied: "0", level:0 },
                    },
                },
            },
        }
    }
};